apiVersion: v1
kind: Pod
metadata:
  name: docker-build
  namespace: jenkins
  labels: 
    app: docker-dind
spec:
  volumes:
  - name: dind-storage
    emptyDir: {}
  containers:
  - name: dind
    image: docker:19.03.3-dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ''
    volumeMounts:
    - name: dind-storage
      mountPath: /var/lib/docker 

---
apiVersion: v1
kind: Service
metadata:
  name: docker-dind
  namespace: jenkins
spec:
  selector:
    app: docker-dind
  ports:
  - protocol: TCP
    port: 2375
    targetPort: 2375
